# Vectorized Backpropagation Lab

Welcome to the vectorized backpropagation lab! By the end of this lab, you will have

- Implemented vectorized and minibatch-compatible forward and backward passes for linear and one-hidden layer neural network regression models with a squared loss

Let's get started!

### Tasks

- Implement a vectorized linear regression model with a squared loss
- Sample a random data point along with weights and compute all gradients via backpropagation

In [1]:
import numpy as np

In [29]:
X = np.array([[x,y] for x,y in zip(np.random.randn(30),np.arange(30))])

In [126]:
X_test =  np.array([[x,y] for x,y in zip(np.random.randn(30),np.arange(30))])

In [125]:
y = np.array([[1],[2]])

In [50]:
X

array([[  0.15984315,   0.        ],
       [ -1.4303778 ,   1.        ],
       [ -1.00547432,   2.        ],
       [  0.13717882,   3.        ],
       [  0.69095079,   4.        ],
       [ -1.14287634,   5.        ],
       [ -1.94506229,   6.        ],
       [ -0.94977362,   7.        ],
       [ -0.39137777,   8.        ],
       [  0.65507012,   9.        ],
       [  1.02265357,  10.        ],
       [  1.51374361,  11.        ],
       [  0.87498696,  12.        ],
       [ -0.95029684,  13.        ],
       [  0.70861428,  14.        ],
       [  0.82448298,  15.        ],
       [  0.37189225,  16.        ],
       [  0.60482664,  17.        ],
       [  2.04955579,  18.        ],
       [  0.52360031,  19.        ],
       [  0.2741994 ,  20.        ],
       [  0.75327266,  21.        ],
       [ -0.30624047,  22.        ],
       [ -0.24245557,  23.        ],
       [ -0.91992197,  24.        ],
       [  0.84674312,  25.        ],
       [ -0.30949268,  26.        ],
 

In [69]:
def linear_matrix_regression(X,y):
    weights = (np.linalg.inv(X.T.dot(X)).dot(X.T)).T.dot(y)
    return weights

In [127]:
weights = linear_matrix_regression(X,y)

In [131]:
# predicted y classes

weights.T @ X_test

array([[-0.1464422,  2.       ]])

### Tasks

- Implement a vectorized one-hidden layer neural network model with a squared loss
- Sample a random data point along with weights and compute all gradients via backpropagation

In [67]:
# Assume ReLu activation function
# [max(W1*X + b1,0)W2 +b2 - y]^2

In [92]:
np.array([np.random.randn() for _ in range(len(X))]).reshape(1,-1)

array([[ 0.47466193, -1.49989851, -0.05585435, -1.5829924 , -1.01169273,
        -0.35085944,  0.60238668,  1.96232331,  0.29034958, -0.68810442,
        -0.38328461, -1.95759932,  0.44863427,  0.8020426 ,  1.4413514 ,
         0.25548877, -0.73080106, -0.30940558, -2.53414437, -1.08210357,
         1.80444895, -1.36027456,  0.27527848, -0.45875562, -1.42604418,
        -1.39220966,  1.53779909, -0.60607826,  0.2582005 ,  0.37659491]])

In [122]:
def one_hidden_layer_matrix(X,y):
    
    # initialize weights
    W1 = np.array([np.random.randn() for _ in range(len(X))]).reshape(1,-1)
    W2 = np.array([np.random.randn() for _ in range(len(X))]).reshape(1,-1)
    # initialize bias
    b1 = np.array([np.random.randn() for _ in range(2)]).reshape(1,-1)
    b2 = np.array([np.random.randn() for _ in range(2)]).reshape(1,-1)
    
    A = W1 @ X
    R = A+b1
    print(R)
    c = np.max((R,0))
    print(c)
    T = c*W2
    y_hat = T+b2
    loss = (y_hat - y)**2
    
    return loss

In [123]:
one_hidden_layer_matrix(X,y)

[[   3.64223896  205.88150416]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [132]:
sdf

NameError: name 'sdf' is not defined

### Tasks

- Implement a vectorized linear regression model with a squared loss with support for mini-batch learning
- Sample a random data point along with weights and compute all gradients via backpropagation

### Tasks

- Implement a vectorized one-hidden layer neural network model with a squared loss with support for mini-batch learning
- Sample a random data point along with weights and compute all gradients via backpropagation

### Bonus Tasks

- Implement a stochastic gradient descent optimizer and optimize these models on a single data points and batches of data points.