# Recurrent Neural Network Layers Lab

Welcome to the recurrent neural networks layers lab! By the end of this lab you will have

- Implemented a RecurrentCell layer
- Implemented a Recurrent layer
- Gradient-checked both of your layers to ensure they are bug-free

Let's get started!

---

# Layer Interface

Recall the interface for a layer.

In [5]:
class Layer:
    def forward(self, inputs):
        raise NotImplementedError('Forward pass not implemented!')
        
    def backward(self, dout):
        raise NotImplementedError('Backward pass not implemented!')

## Task

- Implement a recurrent cell layer according to the computational graph

![RecurrentCell Layer](images/RecurrentCell%20Layer.png)
where $h' = h w_h + x w_x$.

In [16]:
class Recurrent_Layer(Layer):

    def forward(self,x,h,wh,wx):
        self.x = x
        self.h = h
        self.wh = wh
        self.wx= wx
        h_ = h*wh + x*wx
        self.h_ = h_
        return h_
        
    def backward(self,h_):
        dh_ = h_
        dwh = dh_*self.h
        dwx = dh_ * self.x
        
        return dwh, dwx

In [17]:
recurrent_layer = Recurrent_Layer()

In [18]:
x = 4
wh = 2
wx = 1
h = 3

In [19]:
recurrent_layer.forward(x,h,wh,wx)

10

In [20]:
recurrent_layer.backward(1)

(3, 4)

## Task

- Gradient check your recurrent cell

## Requirements

- Run the following code to gradient check your `RecurrentCell` backpropagation code

In [25]:
import numpy as np
from checking import estimate_gradients

recurrent =  Recurrent_Layer()
for input_len in np.random.randint(low=1, high=10, size=10):
    wx, x, wh, h = np.random.randn(4) # random input values
    estimated_grads = estimate_gradients(recurrent.forward, # gradient check
                                         wrt=['wx', 'wh', 'h'],
                                         at={'wx': wx, 'x': x, 'wh': wh, 'h': h})
    exact_grads = recurrent.backward(1)
    print(exact_grads)
#     try:
#         for name, value in zip(['wx', 'wh', 'h'], exact_grads):
#             estimated_grad = estimated_grads[name]
#             difference = abs(estimated_grad - value)
#             assert difference < 1e-3
#     except AssertionError:
#         #print(f'Gradient failed on {name} with difference {difference}!')

ImportError: No module named 'checking'

## Task

- Define a `Recurrent` layer according to the computational graph

![Forward Backward Example](images/Recurrent%20Layer.png)

where $h_{i+1} = h_i w_h + x_i w_x$ for $i > 1$.

## Hint

- Use `RecurrentCell` layers in your implementation

In [11]:
import numpy as np

In [29]:
class Recurrent_Cell_Vector(Layer):
    def forward(self,x,h0,weights):
        inputs = np.vstack((x,h0))
        self.inputs = inputs
        h_ = weights.T @ inputs
        return h_
        
    def backward(self,hn):
        dhn = hn
        dwh = self.inputs[0,:]
        dwx = self.inputs[1,:]
        return dwh, dwx

In [30]:
x = np.array([[1,2,3,4,5]])
h0 = np.array([[4,3,5,2,1]])

In [31]:
wx = 4
wh = 10

In [32]:
weights = np.vstack((wx,wh))

In [33]:
weights.T

array([[ 4, 10]])

In [34]:
inputs = np.vstack((x,h0))

In [35]:
inputs

array([[1, 2, 3, 4, 5],
       [4, 3, 5, 2, 1]])

In [36]:
recurrent_cell_vector = Recurrent_Cell_Vector()

In [37]:
recurrent_cell_vector.forward(x,h0,weights)

array([[44, 38, 62, 36, 30]])

In [38]:
recurrent_cell_vector.backward(1)

(array([1, 2, 3, 4, 5]), array([4, 3, 5, 2, 1]))

## Task

- Gradient check your `Recurrent` layer

## Requirements

- Run the following code to gradient check your `Recurrent` backpropagation code

In [69]:
import numpy as np

for input_len in np.random.randint(low=1, high=10, size=10):
    # Random input length and input values
    recurrent = Recurrent(input_len)
    wh, wx = np.random.randn(2)
    h0 = np.random.randn()
    X = np.random.randn(input_len)

    # Gradient check
    estimated_grads = estimate_gradients(recurrent.forward,
                                         wrt=['wx', 'wh', 'h0'],
                                         at={'wx': wx, 'X': X, 'wh': wh, 'h0': h0})
    exact_grads = recurrent.backward(1)
    try:
        for name, value in zip(['wx', 'wh', 'h0'], exact_grads):
            estimated_grad = estimated_grads[name]
            difference = abs(estimated_grad - value)
            assert difference < 1e-3
    except AssertionError:
        print(f'Gradient failed on {name} with difference {difference}!')

SyntaxError: invalid syntax (<ipython-input-69-1e63c443001d>, line 21)